import type { Role } from "./userRolesService";

export type { Role };

export interface CreateUserForm {
  first_name: string;
  middle_name: string;
  last_name: string;
  email: string;
  passwordType: "manual" | "autogenerated";
  password: string;
  generatedPassword?: string;
  role_ids: string[];
  activeStep: number;
}

export interface CreateUserData {
  first_name: string;
  middle_name: string | null;
  last_name: string;
  email: string;
  password: string;
  role_ids: number[];
}

export interface CreateRoleForm {
  name: string;
  is_faculty: boolean;
  permission_ids: number[];
  activeStep: number;
}