import type { CreateUserForm } from "./types";

/**
 * Validation rules for Create User form
 * Matches EditUserDrawer.tsx validation exactly
 */
export const validateCreateUserForm = {
  first_name: (value: string) => {
    const trimmed = value.trim();
    if (!trimmed) return "First name is required";
    if (trimmed.length > 100)
      return "First name must be 100 characters or less";
    if (!/^[a-zA-Z]+(?:\s[a-zA-Z]+)*$/.test(trimmed))
      return "First name must contain only letters (no extra spaces)";
    return null;
  },

  middle_name: (value: string) => {
    if (!value) return null;
    const trimmed = value.trim();
    if (trimmed.length > 100)
      return "Middle name must be 100 characters or less";
    if (!/^[a-zA-Z]+(?:\s[a-zA-Z]+)*$/.test(trimmed))
      return "Middle name must contain only letters (no extra spaces)";
    return null;
  },

  last_name: (value: string) => {
    const trimmed = value.trim();
    if (!trimmed) return "Last name is required";
    if (trimmed.length > 100)
      return "Last name must be 100 characters or less";
    if (!/^[a-zA-Z]+(?:\s[a-zA-Z]+)*$/.test(trimmed))
      return "Last name must contain only letters (no extra spaces)";
    return null;
  },

  email: (value: string) => {
    const trimmed = value.trim();
    if (!trimmed) return "Email is required";
    if (trimmed.length > 255) return "Email must be 255 characters or less";
    if (!/^\S+@\S+\.\S+$/.test(trimmed)) return "Invalid email format";
    return null;
  },

  password: (value: string, values: CreateUserForm) => {
    if (values.passwordType === "autogenerated") return null;
    if (!value) return "Password is required";
    if (value.length < 8) return "Password must be at least 8 characters";
    if (!/[0-9]/.test(value)) return "Password must include a number";
    if (!/[a-z]/.test(value))
      return "Password must include a lowercase letter";
    if (!/[A-Z]/.test(value))
      return "Password must include an uppercase letter";
    if (!/[$&+,:;=?@#|'<>.^*()%!-]/.test(value))
      return "Password must include a special symbol";
    return null;
  },

  role_ids: (value: string[]) => {
    if (!value || value.length === 0) return "Select at least one role";
    return null;
  },
};

/**
 * Validation rules for Create Role form
 * Matches EditRoleDrawer.tsx validation exactly
 */

export const validateCreateRoleForm = {
  name: (value: string) => {
    const trimmed = value.trim();
    if (!trimmed) return "Role Name is required";
    if (trimmed.length > 50) return "Name must be 50 characters or less";
    return null;
  },

  description: (value: string) => {
    const trimmed = value.trim();
    if (trimmed.length > 255) return "Role Description must be 255 characters or less";
    return null;
  },

  permission_ids: (value: number[]) => {
    if (!value || value.length === 0) return "Select at least one permission";
    return null;
  },
};
