"use client";

import { useState } from "react";
import {
  Box,
  Text,
  Grid,
  Group,
  ActionIcon,
  Alert,
  ThemeIcon,
} from "@mantine/core";
import { IconEye, IconEyeOff, IconAlertTriangle } from "@tabler/icons-react";
import type { UseFormReturnType } from "@mantine/form";
import type { CreateUserForm } from "../_lib/types";
import type { Role } from "../_lib/userRolesService";

const PRINCIPAL_ROLE_NAME = "Principal";

interface StepReviewProps {
  form: UseFormReturnType<CreateUserForm>;
  availableRoles: Role[];
  principalWarning: boolean;
}

export default function StepReview({
  form,
  availableRoles,
  principalWarning,
}: StepReviewProps) {
  const [showPassword, setShowPassword] = useState(false);

  const selectedRoles = form.values.role_ids
    .map((roleId) =>
      availableRoles.find((r) => r.role_id.toString() === roleId),
    )
    .filter((role): role is Role => role !== undefined);

  const hasPrincipal = selectedRoles.some(
    (r) => r.name === PRINCIPAL_ROLE_NAME,
  );

  return (
    <Box>
      <Text size="xl" fw={700} mb="md" c="#298925">
        Review and Create
      </Text>

      <Box
        p="lg"
        w="100%"
        style={{
          border: "1px solid #B8B8B8",
          borderRadius: "8px",
          minWidth: 0,
        }}
      >
        <Text size="sm" c="gray.7" mb="md">
          Please ensure all information is correct. You can still return to
          previous steps to edit.
        </Text>

        {/* Principal warning alert */}
        {principalWarning && hasPrincipal && (
          <Alert
            variant="filled"
            radius="md"
            mb="md"
            styles={{
              root: { backgroundColor: "#fae173" },
              icon: { alignSelf: "center", marginTop: 0 },
            }}
            icon={
              <ThemeIcon color="#2A2A2A" variant="transparent" size="md">
                <IconAlertTriangle size={20} />
              </ThemeIcon>
            }
          >
            <Text fw={700} size="sm" c="#2A2A2A">
              Principal Role Warning
            </Text>
            <Text size="sm" fs="italic" c="#2A2A2A">
              A user with the <strong>Principal</strong> role already exists.
              Assigning this role to another user may cause conflicts. Proceed
              only if this is intentional.
            </Text>
          </Alert>
        )}

        {/* User Information Summary */}
        <Box
          p="lg"
          w="100%"
          style={{
            border: "1px solid #B8B8B8",
            borderRadius: "8px",
            minWidth: 0,
          }}
          mb="sm"
        >
          <Text size="lg" fw={700} mb="md" c="#298925">
            User Information
          </Text>

          <Grid gutter="md">
            <Grid.Col span={{ base: 12, sm: 4 }}>
              <Text size="sm" fw={600}>
                First Name
              </Text>
              <Text size="sm">{form.values.first_name || "First Name"}</Text>
            </Grid.Col>

            <Grid.Col span={{ base: 12, sm: 4 }}>
              <Text size="sm" fw={600}>
                Middle Name
              </Text>
              <Text
                size="sm"
                c={form.values.middle_name.trim() ? undefined : "dimmed"}
              >
                {form.values.middle_name.trim() || <i>Blank</i>}
              </Text>
            </Grid.Col>

            <Grid.Col span={{ base: 12, sm: 4 }}>
              <Text size="sm" fw={600}>
                Last Name
              </Text>
              <Text size="sm">{form.values.last_name || "Last Name"}</Text>
            </Grid.Col>
          </Grid>

          <Grid gutter="md" mt="md">
            <Grid.Col span={{ base: 12, sm: 6 }}>
              <Text size="sm" fw={600}>
                Email
              </Text>
              <Text size="sm">{form.values.email || "Email"}</Text>
            </Grid.Col>

            <Grid.Col span={{ base: 12, sm: 6 }}>
              <Text size="sm" fw={600}>
                Password
              </Text>
              <Group gap={6} align="center">
                <Text size="sm">
                  {showPassword
                    ? form.values.passwordType === "autogenerated"
                      ? form.values.generatedPassword
                      : form.values.password
                    : "••••••••"}
                </Text>
                <ActionIcon
                  variant="subtle"
                  size="xs"
                  color="gray"
                  onClick={() => setShowPassword((v) => !v)}
                  aria-label={showPassword ? "Hide password" : "Show password"}
                >
                  {showPassword ? (
                    <IconEyeOff size={14} />
                  ) : (
                    <IconEye size={14} />
                  )}
                </ActionIcon>
              </Group>
            </Grid.Col>
          </Grid>
        </Box>

        {/* Role Summary */}
        <Box
          p="lg"
          w="100%"
          style={{
            border: "1px solid #B8B8B8",
            borderRadius: "8px",
            minWidth: 0,
          }}
        >
          <Text size="lg" fw={700} mb="md" c="#298925">
            Roles Assignment
          </Text>

          {selectedRoles.length > 0 ? (
            selectedRoles.map((role, index) => (
              <Group key={role.role_id} gap="sm" mb="xs">
                <Box
                  style={{
                    width: 24,
                    height: 24,
                    borderRadius: 4,
                    backgroundColor: "#e9ecef",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                >
                  <Text size="xs" fw={600} c="dimmed">
                    {index + 1}
                  </Text>
                </Box>
                <Text size="sm">{role.name}</Text>
              </Group>
            ))
          ) : (
            <Text size="sm" c="red">
              No roles selected
            </Text>
          )}
        </Box>
      </Box>
    </Box>
  );
}
